language: ruby
rvm:
  - 2.0.0-p195

env:
  - DB=postgresql

script:
  - RAILS_ENV=test bundle exec rake --trace db:migrate test

before_script:
  - sudo apt-get install libimage-exiftool-perl graphicsmagick
  - psql -c 'create database updates_development' -U postgres

notifications:
  email: false
