language: ruby
rvm:
  - 2.0.0-p195

env:
  - DB=postgresql

script:
  - RAILS_ENV=test bundle exec rake db:migrate --trace
  - bundle exec rake test:prepare
  - bundle exec rake

before_script:
  - cp config/database.yml.example config/database.yml
  - psql -c 'create database updates_test' -U postgres

notifications:
  email: false
